#!/usr/bin/env perl

$pdf_mode      = 3;
$max_repeat    = 5;
$latex         = 'platex -shell-escape -halt-on-error';
$latex_silent  = 'platex -shell-escape -halt-on-error -interaction=batchmode';
$clean_ext     = '%R.dvi';
$bibtex        = 'pbibtex';
$dvipdf        = 'dvipdfmx %O -o %D %S';
$makeindex     = 'mendex %O -o %D %S';
