[tools]
node = "22"
java = "21.0.5+11.0.LTS"
quarkus = "latest"

"npm:pnpm" = "latest"
"npm:@antfu/ni" = "latest"
"npm:local-web-server" = "latest"
"npm:npm-check-updates" = "latest"

[settings]
experimental = true
