cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "curl"
brew "exa"
brew "fzf"
brew "ghq"
brew "git"
brew "github/gh/gh"
brew "jq"
brew "loc"
brew "mas"
brew "nkf"
brew "starship"
brew "volta"
brew "watchman"
brew "wget"
brew "zplug"

cask "appcleaner"
cask "authy"
cask "discord"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "muzzle"
cask "one-switch"
cask "simplenote"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "workflowy"

mas "Battery Indicator", id: 1206020918
mas "Gifox", id: 1082624744
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "NextDNS", id: 1464122853
mas "Pages", id: 409201541
mas "Spark", id: 1176895641
mas "Tweetbot", id: 1384080005
mas "Yoink", id: 457622435
