code --install-extension chrisbibby.hide-node-modules
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension Pivotal.vscode-spring-boot
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension tamasfe.even-better-toml
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-boot-dashboard
code --install-extension vscjava.vscode-spring-initializr
code --install-extension wmaurer.change-case