code --install-extension bierner.markdown-preview-github-styles
code --install-extension dbaeumer.vscode-eslint
code --install-extension denoland.vscode-deno
code --install-extension esbenp.prettier-vscode
code --install-extension GraphQL.vscode-graphql
code --install-extension hbenl.vscode-test-explorer
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension kavod-io.vscode-jest-test-adapter
code --install-extension mechatroner.rainbow-csv
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-vscode.test-adapter-converter
code --install-extension PKief.material-icon-theme
code --install-extension Prisma.prisma
code --install-extension qezhu.gitlink
code --install-extension tamasfe.even-better-toml
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wmaurer.change-case