code --install-extension bierner.markdown-preview-github-styles
code --install-extension dbaeumer.vscode-eslint
code --install-extension denoland.vscode-deno
code --install-extension esbenp.prettier-vscode
code --install-extension monokai.theme-monokai-pro-vscode
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension PKief.material-icon-theme
code --install-extension qezhu.gitlink
code --install-extension tamasfe.even-better-toml
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wmaurer.change-case
