#!/usr/bin/env zsh

zstyle ':completion::complete:*' use-cache true
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' list-colors "${LS_COLORS}"

setopt no_beep
setopt auto_cd
setopt auto_pushd
setopt auto_menu
setopt list_packed
setopt list_types
setopt pushd_ignore_dups
setopt correct
setopt magic_equal_subst
setopt complete_aliases
setopt extended_glob
setopt nonomatch
setopt share_history
setopt extended_history
setopt inc_append_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_reduce_blanks

unsetopt caseglob
unsetopt promptcr

export TZ="Asia/Tokyo"
export LESS="-R"
export LANG="ja_JP.utf8"
export EDITOR="code --wait"
export FCEDIT="code --wait"

export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:="${HOME}/.config"}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:="${HOME}/.cache"}
export XDG_DATA_HOME=${XDG_DATA_HOME:="${HOME}/.local/share"}
export XDG_STATE_HOME=${XDG_STATE_HOME:="${HOME}/.local/state"}

export HISTFILE="${HOME}/.zsh_history"
export HISTSIZE=100000
export SAVEHIST=1000000

export FZF_DEFAULT_OPTS=" \
--color=bg+:#363a4f,bg:#24273a,spinner:#f4dbd6,hl:#ed8796 \
--color=fg:#cad3f5,header:#ed8796,info:#c6a0f6,pointer:#f4dbd6 \
--color=marker:#f4dbd6,fg+:#cad3f5,prompt:#c6a0f6,hl+:#ed8796 \
--height 40% --ansi --cycle --reverse --select-1 --exit-0"

export AQUA_GLOBAL_CONFIG=${AQUA_GLOBAL_CONFIG:-}:${XDG_CONFIG_HOME:-$HOME/.config}/aquaproj-aqua/aqua.yaml
export AQUA_ROOT_DIR=${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua

path+=(
  "${AQUA_ROOT_DIR}/bin"
  "${HOME}/.local/bin"
)

fpath+=(
  "${XDG_DATA_HOME}/zsh/pure"
)

typeset -U path PATH

eval "$(mise activate zsh)"
eval "$(atuin init zsh --disable-up-arrow)"

source "${XDG_CONFIG_HOME}/zsh/alias.zsh"
source "${XDG_CONFIG_HOME}/zsh/function.zsh"
source "${XDG_DATA_HOME}/zsh/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh"
source "${XDG_DATA_HOME}/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh"

zle -N fzf_ghq
bindkey '^g' fzf_ghq

zle -N fzf_switch
bindkey '^b' fzf_switch

autoload -Uz colors; colors
autoload -Uz compinit; compinit
autoload -Uz promptinit; promptinit

prompt pure
