#!/usr/bin/env zsh

autoload -Uz compinit; compinit
autoload -Uz colors; colors

zstyle ':completion::complete:*' use-cache true
zstyle ':completion:*:default' menu select=1
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' list-colors "${LS_COLORS}"

setopt no_beep
setopt auto_cd
setopt auto_pushd
setopt auto_menu
setopt list_packed
setopt list_types
setopt pushd_ignore_dups
setopt correct
setopt magic_equal_subst
setopt complete_aliases
setopt extended_glob
setopt nonomatch
setopt share_history
setopt extended_history
setopt inc_append_history
setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_reduce_blanks

unsetopt caseglob
unsetopt promptcr

typeset -U path PATH

export PATH="/usr/local/go/bin:$HOME/.fnm:$HOME/.local/bin:$PATH"

export GOPATH="$HOME/.go"

export FZF_DEFAULT_OPTS=" \
--color=bg+:#363a4f,bg:#24273a,spinner:#f4dbd6,hl:#ed8796 \
--color=fg:#cad3f5,header:#ed8796,info:#c6a0f6,pointer:#f4dbd6 \
--color=marker:#f4dbd6,fg+:#cad3f5,prompt:#c6a0f6,hl+:#ed8796 \
--height 40% --ansi --cycle --reverse --select-1 --exit-0 --bind=tab:down --bind=btab:up"


eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
eval "$(fnm env --use-on-cd)"
eval "$(starship init zsh)"

source "$HOME/.cargo/env"
source "$HOME/.sdkman/bin/sdkman-init.sh"

source $XDG_CONFIG_HOME/zsh/plugin/zsh-completions/zsh-completions.plugin.zsh
source $XDG_CONFIG_HOME/zsh/plugin/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
source $XDG_CONFIG_HOME/zsh/plugin/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
source $XDG_CONFIG_HOME/zsh/plugin/zsh-history-substring-search/zsh-history-substring-search.plugin.zsh

source $XDG_CONFIG_HOME/zsh/alias.zsh
source $XDG_CONFIG_HOME/zsh/function.zsh

zle -N fzf_history
bindkey '^r' fzf_history

zle -N fzf_ghq
bindkey '^g' fzf_ghq

zle -N fzf_switch
bindkey '^b' fzf_switch
