export LESS="-R"
export LANG="ja_JP.UTF-8"
export LC_ALL="ja_JP.UTF-8"
export EDITOR="code --wait"
export FCEDIT="code --wait"

export XDG_CONFIG_HOME="$HOME/.config"

export VOLTA_HOME="$HOME/.volta"

export HISTFILE="$HOME/.zhistory"
export HISTSIZE=100000
export SAVEHIST=100000

export FZF_DEFAULT_OPTS="--height 40% --ansi --cycle --reverse --select-1 --exit-0 --bind=tab:down --bind=btab:up"

export PATH="$VOLTA_HOME/bin:$PATH"
